// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/mcglynn/rvo/data/car_controller_protos.proto

package com.mcglynn.rvo.data;

public final class CarControlProtos {
  private CarControlProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CarControllerCommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CarControllerCommand)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 time = 1;</code>
     */
    long getTime();

    /**
     * <code>uint32 brake = 2;</code>
     */
    int getBrake();

    /**
     * <code>uint32 throttle = 3;</code>
     */
    int getThrottle();

    /**
     * <code>sint32 steer = 4;</code>
     */
    int getSteer();

    /**
     * <code>bool reverse = 5;</code>
     */
    boolean getReverse();
  }
  /**
   * Protobuf type {@code CarControllerCommand}
   */
  public  static final class CarControllerCommand extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CarControllerCommand)
      CarControllerCommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CarControllerCommand.newBuilder() to construct.
    private CarControllerCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CarControllerCommand() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CarControllerCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              time_ = input.readUInt64();
              break;
            }
            case 16: {

              brake_ = input.readUInt32();
              break;
            }
            case 24: {

              throttle_ = input.readUInt32();
              break;
            }
            case 32: {

              steer_ = input.readSInt32();
              break;
            }
            case 40: {

              reverse_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mcglynn.rvo.data.CarControlProtos.internal_static_CarControllerCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mcglynn.rvo.data.CarControlProtos.internal_static_CarControllerCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand.class, com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand.Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>uint64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int BRAKE_FIELD_NUMBER = 2;
    private int brake_;
    /**
     * <code>uint32 brake = 2;</code>
     */
    public int getBrake() {
      return brake_;
    }

    public static final int THROTTLE_FIELD_NUMBER = 3;
    private int throttle_;
    /**
     * <code>uint32 throttle = 3;</code>
     */
    public int getThrottle() {
      return throttle_;
    }

    public static final int STEER_FIELD_NUMBER = 4;
    private int steer_;
    /**
     * <code>sint32 steer = 4;</code>
     */
    public int getSteer() {
      return steer_;
    }

    public static final int REVERSE_FIELD_NUMBER = 5;
    private boolean reverse_;
    /**
     * <code>bool reverse = 5;</code>
     */
    public boolean getReverse() {
      return reverse_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (time_ != 0L) {
        output.writeUInt64(1, time_);
      }
      if (brake_ != 0) {
        output.writeUInt32(2, brake_);
      }
      if (throttle_ != 0) {
        output.writeUInt32(3, throttle_);
      }
      if (steer_ != 0) {
        output.writeSInt32(4, steer_);
      }
      if (reverse_ != false) {
        output.writeBool(5, reverse_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, time_);
      }
      if (brake_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, brake_);
      }
      if (throttle_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, throttle_);
      }
      if (steer_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(4, steer_);
      }
      if (reverse_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, reverse_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand)) {
        return super.equals(obj);
      }
      com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand other = (com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand) obj;

      if (getTime()
          != other.getTime()) return false;
      if (getBrake()
          != other.getBrake()) return false;
      if (getThrottle()
          != other.getThrottle()) return false;
      if (getSteer()
          != other.getSteer()) return false;
      if (getReverse()
          != other.getReverse()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + BRAKE_FIELD_NUMBER;
      hash = (53 * hash) + getBrake();
      hash = (37 * hash) + THROTTLE_FIELD_NUMBER;
      hash = (53 * hash) + getThrottle();
      hash = (37 * hash) + STEER_FIELD_NUMBER;
      hash = (53 * hash) + getSteer();
      hash = (37 * hash) + REVERSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getReverse());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CarControllerCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CarControllerCommand)
        com.mcglynn.rvo.data.CarControlProtos.CarControllerCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mcglynn.rvo.data.CarControlProtos.internal_static_CarControllerCommand_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mcglynn.rvo.data.CarControlProtos.internal_static_CarControllerCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand.class, com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand.Builder.class);
      }

      // Construct using com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        time_ = 0L;

        brake_ = 0;

        throttle_ = 0;

        steer_ = 0;

        reverse_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mcglynn.rvo.data.CarControlProtos.internal_static_CarControllerCommand_descriptor;
      }

      @java.lang.Override
      public com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand getDefaultInstanceForType() {
        return com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand.getDefaultInstance();
      }

      @java.lang.Override
      public com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand build() {
        com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand buildPartial() {
        com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand result = new com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand(this);
        result.time_ = time_;
        result.brake_ = brake_;
        result.throttle_ = throttle_;
        result.steer_ = steer_;
        result.reverse_ = reverse_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand) {
          return mergeFrom((com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand other) {
        if (other == com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand.getDefaultInstance()) return this;
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getBrake() != 0) {
          setBrake(other.getBrake());
        }
        if (other.getThrottle() != 0) {
          setThrottle(other.getThrottle());
        }
        if (other.getSteer() != 0) {
          setSteer(other.getSteer());
        }
        if (other.getReverse() != false) {
          setReverse(other.getReverse());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long time_ ;
      /**
       * <code>uint64 time = 1;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>uint64 time = 1;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 time = 1;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private int brake_ ;
      /**
       * <code>uint32 brake = 2;</code>
       */
      public int getBrake() {
        return brake_;
      }
      /**
       * <code>uint32 brake = 2;</code>
       */
      public Builder setBrake(int value) {
        
        brake_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 brake = 2;</code>
       */
      public Builder clearBrake() {
        
        brake_ = 0;
        onChanged();
        return this;
      }

      private int throttle_ ;
      /**
       * <code>uint32 throttle = 3;</code>
       */
      public int getThrottle() {
        return throttle_;
      }
      /**
       * <code>uint32 throttle = 3;</code>
       */
      public Builder setThrottle(int value) {
        
        throttle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 throttle = 3;</code>
       */
      public Builder clearThrottle() {
        
        throttle_ = 0;
        onChanged();
        return this;
      }

      private int steer_ ;
      /**
       * <code>sint32 steer = 4;</code>
       */
      public int getSteer() {
        return steer_;
      }
      /**
       * <code>sint32 steer = 4;</code>
       */
      public Builder setSteer(int value) {
        
        steer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 steer = 4;</code>
       */
      public Builder clearSteer() {
        
        steer_ = 0;
        onChanged();
        return this;
      }

      private boolean reverse_ ;
      /**
       * <code>bool reverse = 5;</code>
       */
      public boolean getReverse() {
        return reverse_;
      }
      /**
       * <code>bool reverse = 5;</code>
       */
      public Builder setReverse(boolean value) {
        
        reverse_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool reverse = 5;</code>
       */
      public Builder clearReverse() {
        
        reverse_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CarControllerCommand)
    }

    // @@protoc_insertion_point(class_scope:CarControllerCommand)
    private static final com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand();
    }

    public static com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CarControllerCommand>
        PARSER = new com.google.protobuf.AbstractParser<CarControllerCommand>() {
      @java.lang.Override
      public CarControllerCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CarControllerCommand(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CarControllerCommand> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CarControllerCommand> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mcglynn.rvo.data.CarControlProtos.CarControllerCommand getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CarDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CarData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 time = 1;</code>
     */
    long getTime();

    /**
     * <code>bool happy = 2;</code>
     */
    boolean getHappy();
  }
  /**
   * Protobuf type {@code CarData}
   */
  public  static final class CarData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CarData)
      CarDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CarData.newBuilder() to construct.
    private CarData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CarData() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CarData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              time_ = input.readUInt64();
              break;
            }
            case 16: {

              happy_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mcglynn.rvo.data.CarControlProtos.internal_static_CarData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mcglynn.rvo.data.CarControlProtos.internal_static_CarData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mcglynn.rvo.data.CarControlProtos.CarData.class, com.mcglynn.rvo.data.CarControlProtos.CarData.Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>uint64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int HAPPY_FIELD_NUMBER = 2;
    private boolean happy_;
    /**
     * <code>bool happy = 2;</code>
     */
    public boolean getHappy() {
      return happy_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (time_ != 0L) {
        output.writeUInt64(1, time_);
      }
      if (happy_ != false) {
        output.writeBool(2, happy_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, time_);
      }
      if (happy_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, happy_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mcglynn.rvo.data.CarControlProtos.CarData)) {
        return super.equals(obj);
      }
      com.mcglynn.rvo.data.CarControlProtos.CarData other = (com.mcglynn.rvo.data.CarControlProtos.CarData) obj;

      if (getTime()
          != other.getTime()) return false;
      if (getHappy()
          != other.getHappy()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + HAPPY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHappy());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mcglynn.rvo.data.CarControlProtos.CarData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mcglynn.rvo.data.CarControlProtos.CarData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mcglynn.rvo.data.CarControlProtos.CarData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CarData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CarData)
        com.mcglynn.rvo.data.CarControlProtos.CarDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mcglynn.rvo.data.CarControlProtos.internal_static_CarData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mcglynn.rvo.data.CarControlProtos.internal_static_CarData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mcglynn.rvo.data.CarControlProtos.CarData.class, com.mcglynn.rvo.data.CarControlProtos.CarData.Builder.class);
      }

      // Construct using com.mcglynn.rvo.data.CarControlProtos.CarData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        time_ = 0L;

        happy_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mcglynn.rvo.data.CarControlProtos.internal_static_CarData_descriptor;
      }

      @java.lang.Override
      public com.mcglynn.rvo.data.CarControlProtos.CarData getDefaultInstanceForType() {
        return com.mcglynn.rvo.data.CarControlProtos.CarData.getDefaultInstance();
      }

      @java.lang.Override
      public com.mcglynn.rvo.data.CarControlProtos.CarData build() {
        com.mcglynn.rvo.data.CarControlProtos.CarData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mcglynn.rvo.data.CarControlProtos.CarData buildPartial() {
        com.mcglynn.rvo.data.CarControlProtos.CarData result = new com.mcglynn.rvo.data.CarControlProtos.CarData(this);
        result.time_ = time_;
        result.happy_ = happy_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mcglynn.rvo.data.CarControlProtos.CarData) {
          return mergeFrom((com.mcglynn.rvo.data.CarControlProtos.CarData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mcglynn.rvo.data.CarControlProtos.CarData other) {
        if (other == com.mcglynn.rvo.data.CarControlProtos.CarData.getDefaultInstance()) return this;
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getHappy() != false) {
          setHappy(other.getHappy());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mcglynn.rvo.data.CarControlProtos.CarData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mcglynn.rvo.data.CarControlProtos.CarData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long time_ ;
      /**
       * <code>uint64 time = 1;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>uint64 time = 1;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 time = 1;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private boolean happy_ ;
      /**
       * <code>bool happy = 2;</code>
       */
      public boolean getHappy() {
        return happy_;
      }
      /**
       * <code>bool happy = 2;</code>
       */
      public Builder setHappy(boolean value) {
        
        happy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool happy = 2;</code>
       */
      public Builder clearHappy() {
        
        happy_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CarData)
    }

    // @@protoc_insertion_point(class_scope:CarData)
    private static final com.mcglynn.rvo.data.CarControlProtos.CarData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mcglynn.rvo.data.CarControlProtos.CarData();
    }

    public static com.mcglynn.rvo.data.CarControlProtos.CarData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CarData>
        PARSER = new com.google.protobuf.AbstractParser<CarData>() {
      @java.lang.Override
      public CarData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CarData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CarData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CarData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mcglynn.rvo.data.CarControlProtos.CarData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CarControllerCommand_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CarControllerCommand_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CarData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CarData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0com/mcglynn/rvo/data/car_controller_pr" +
      "otos.proto\"e\n\024CarControllerCommand\022\014\n\004ti" +
      "me\030\001 \001(\004\022\r\n\005brake\030\002 \001(\r\022\020\n\010throttle\030\003 \001(" +
      "\r\022\r\n\005steer\030\004 \001(\021\022\017\n\007reverse\030\005 \001(\010\"&\n\007Car" +
      "Data\022\014\n\004time\030\001 \001(\004\022\r\n\005happy\030\002 \001(\010B(\n\024com" +
      ".mcglynn.rvo.dataB\020CarControlProtosb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CarControllerCommand_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CarControllerCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CarControllerCommand_descriptor,
        new java.lang.String[] { "Time", "Brake", "Throttle", "Steer", "Reverse", });
    internal_static_CarData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CarData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CarData_descriptor,
        new java.lang.String[] { "Time", "Happy", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
